### ISSUE TITLE
Not working with mixed active content in firefox

### ISSUE THREAD

**Issue by s1-ranjan** [justoverclockl/geo-weather#1] opened 2021-08-09 18:37 UTC
Firefox blocks the mixed active contents in Firefox, please have a look at the following image
![Screenshot from 2021-08-10 00-00-03](https://user-images.githubusercontent.com/20767253/128756652-6fe76868-8005-4cbc-86c9-b49b42d23f2d.png)

**Comment by justoverclockl** [comment] 2021-08-09 20:51
The best strategy to avoid mixed content blocking is to serve all the content as HTTPS instead of HTTP

**Comment by justoverclockl** [comment] 2021-08-09 20:53
I will fix this asap

**Comment by justoverclockl** [comment] 2021-08-09 20:56
Can you try now with last update?
should be fixed

**Closed as completed** 2021-08-10 14:30 UTC

**Comment by s1-ranjan** [comment] 2021-08-11 10:33
no its not working

**Comment by s1-ranjan** [comment] 2021-08-11 10:42
By changing http://api.openweathermap.org/data/2.5/onecall?lat="+t+"&lon="+o+"&lang="+(r.a.forum.attribute("lang")||"en")+"&appid= to https://api.openweathermap.org/data/2.5/onecall?lat="+t+"&lon="+o+"&lang="+(r.a.forum.attribute("lang")||"en")+"&appid= in forum.js file located in /var/www/flarum/vendor/justoverclock/geo-weather/js/dist fixed my issue

**Comment by justoverclockl** [comment] 2021-08-11 10:57
i've make these changes into last version :) so if you update the extension and clear cache, the issue is fixed :)

reference: https://github.com/justoverclockl/geo-weather/blob/main/js/src/forum/GeoWeather.js#L28

**Comment by justoverclockl** [comment] 2021-08-11 11:44
be sure that u are running on 0.1.7 version
